import pandas as pd
df=pd.read_csv("superstore_cleaned.csv", encoding="latin1")
df["Order Date"]=pd.to_datetime(df["Order Date"]); df["Ship Date"]=pd.to_datetime(df["Ship Date"])
df["Shipping Days"]=(df["Ship Date"]-df["Order Date"]).dt.days
print("Revenue:",df.Sales.sum()); print("Profit:",df.Profit.sum())
print("Orders:",df["Order ID"].nunique()); print("Customers:",df["Customer ID"].nunique())
print("\nCategory performance:")
print(df.groupby("Category").agg(Sales=("Sales","sum"),Profit=("Profit","sum")))
print("\nRegional performance:")
print(df.groupby("Region").agg(Sales=("Sales","sum"),Profit=("Profit","sum")))
print("\nTop customers:")
print(df.groupby(["Customer ID","Customer Name"]).Sales.sum().sort_values(ascending=False).head(10))
print("\nTop products by profit:")
print(df.groupby(["Product ID","Product Name"]).Profit.sum().sort_values(ascending=False).head(10))
print("\nBottom products by profit:")
print(df.groupby(["Product ID","Product Name"]).Profit.sum().sort_values().head(10))
print("\nDiscount vs profit:")
print(df.groupby("Discount").agg(Sales=("Sales","sum"),Profit=("Profit","sum")))
print("\nShipping:")
print(df.groupby("Ship Mode")["Shipping Days"].mean())
